Agrega hotfix
nicolas-alv3/menti-unq-frontend pull request #12
Opened 2022-09-29 23:10 UTC by nicolas-alv3

Fixea la pagina de inicio para que no aparezca la barra de abajo 
![image](https://user-images.githubusercontent.com/42628386/193157805-331f4566-d751-4180-aabf-088c4a09a14f.png)

2022-10-03 20:49 UTC, lhazuca requested changes

2022-10-03 20:49 UTC, lhazuca commented on package.json
> +  "proxy": "http://localhost:8080",
Estamos seguros que quermeos esto?

2022-10-03 20:49 UTC, lhazuca commented on src/components/PresentationsList.jsx
> +    return <>
Habria que pone este condicional del lado de donde se monta el componente

2022-10-04 22:43 UTC, nicolas-alv3 commented on src/components/PresentationsList.jsx
> +    return <>
Listop

2022-10-07 17:42 UTC, lhazuca approved these changes

2022-10-07 17:42 UTC, merged