Agrega respuestas basicas
nicolas-alv3/menti-unq-frontend pull request #15
Opened 2022-10-16 15:15 UTC by nicolas-alv3

2022-10-16 15:15 UTC, nicolas-alv3 commented
Agrega respuestas basicas, el PR todavia esta en WIP, dejo una preview
https://www.loom.com/share/213637b4907742bfb6b8c6d4621b8f84

2022-10-16 20:51 UTC, nicolas-alv3 commented
https://www.loom.com/share/329fc8167bf340f0bb79c916138d38ca actualizo preview, creo que con esto ya estamos para el alcance de este PR, habría que agregar validaciones, por ejemplo que el index de la slide actual  no sea mayor a la cantidad de slides -1 y tambien hacer el poll para actualizar los resultados

2022-10-17 00:32 UTC, lhazuca requested changes

2022-10-17 00:32 UTC, lhazuca commented on src/App.js
> +            <Route path='/:id' element={<AnswerPresentationPage/>}/>
Le agregaria algo tipo `/presentation`

2022-10-17 00:32 UTC, lhazuca commented on src/components/PresentPresentationPage.jsx
> +                    console.log("Hubo un error fetcheando las answers")
```suggestion
                    console.log("Hubo un error obteniendo las respuestas")
```

🇪🇸 ✊

2022-10-17 00:32 UTC, lhazuca commented on src/components/PresentPresentationPage.jsx
> +    let {id} = useParams();
```suggestion
    const {id} = useParams();
```

2022-10-17 17:34 UTC, nicolas-alv3 commented on src/App.js
> +            <Route path='/:id' element={<AnswerPresentationPage/>}/>
Listo :ok_hand:

2022-10-19 23:27 UTC, lhazuca requested changes
Marque algunas cositas que me parece interesante resolver. Sobre todo la parte de `.then`

2022-10-19 23:27 UTC, lhazuca commented on src/components/Home.jsx
>      useEffect(() => {
Hmmm...entiendo el refactor para darle un nombre, me parece que esta a la mitad. Me cuesta ver el valor de moverlo asi. Quizas usar una named function para darle nombre, porque aca tmb falta pasarle `fetchPresentations` como dependencia en el array de dependencias quizas definir algo como
```
useEffect(function fetchPresentations() {
PresentationService.getPresentations().then(presentations => {
            setPresentations(presentations)
        }).catch((e) => {
            console.log("error", e)
        })
})
```

2022-10-19 23:27 UTC, lhazuca commented on src/components/PresentPresentationPage.jsx
> +    function fetchPresentation() {
me triggerea un toq la inconsistencia al momento de usar named functions y arrow functions

2022-10-19 23:27 UTC, lhazuca commented on src/components/PresentPresentationPage.jsx
> +        fetchPresentation()
Entiendo que lo que buscas aca (sobre todo con el retry arriba) es traer las respuestas para cuando tengamos una presentacion? es solucionable aprovechando el asincronismo, no hacer `fetchAnswers` hasta que se complete el `fetchPresentation`, eso lo haces con el `.then`

2022-10-19 23:45 UTC, lhazuca approved these changes
Charlado, tiene sentido el pull en loop para ir actualizando las respuestas

2022-10-19 23:47 UTC, merged